project:
  type: website
  output-dir: docs

website:
  title: "Paul Roback"
  navbar:
    background: primary
    search: true
    left:
      - file: index.qmd
        text: "Home"
      - sidebar:mini_project1

  sidebar:
    - id: mini_project1
      title: "Mini Project 1"
      contents:
        - 02_maps_part1.qmd
        - 03_maps_part2.qmd

  page-footer:
    left: |
      &copy; Paul Roback, 2024<br>
      All content licensed under ![](https://static.thenounproject.com/png/70967-200.png){height=20px} ([CC BY-NC-SA 4.0](http://creativecommons.org/licenses/by-nc-sa/4.0/))
    right: |
      Site built with [Quarto](https://quarto.org/)

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    code-overflow: wrap

editor: source
